#ifndef __MTCR_SCK_HPP__
#define __MTCR_SCK_HPP__

#include <winsock2.h>
#define MTCR_PROTOCOL_VERSION 0x01
#define MTCR_MAX_SOCKET_LENGTH 4095

#define MTCR_SERVER_VERSION                 0x00
#define MTCR_SERVER_JOIN_SUCCESSED          0x10
#define MTCR_SERVER_JOIN_FAILED             0x11
#define MTCR_SERVER_PASSWORD_REQUIRED       0x20
#define MTCR_SERVER_PASSWORD_INCORRECT      0x21
#define MTCR_SERVER_USER_JOINED             0x30
#define MTCR_SERVER_USER_LEAVED             0x31
#define MTCR_SERVER_USER_CHANGE_NICKNAME    0x40
#define MTCR_SERVER_CHANGE_NICKNAME_OKAY    0x41
#define MTCR_SERVER_CHANGE_NICKNAME_FAIL    0x42
#define MTCR_SERVER_MSG_SEND                0x50
#define MTCR_SERVER_MSG_SEND_PRIVATE        0x51
#define MTCR_SERVER_MSG_SEND_PRIVATE_OKAY   0x52
#define MTCR_SERVER_MSG_SEND_PRIVATE_FAILED 0x53
#define MTCR_SERVER_MSG_SEND_SERVER         0x54
#define MTCR_SERVER_MSG_SEND_SERVER_PRIVATE 0x55
#define MTCR_SERVER_ONLINE_LIST             0x60
#define MTCR_SERVER_CANNOT_UNDERSTAND       0xFF

#define MTCR_CLIENT_GET_VERSION     0x00
#define MTCR_CLIENT_JOIN            0x10
#define MTCR_CLIENT_PASSWORD        0x20
#define MTCR_CLIENT_CHANGE_NICKNAME 0x40
#define MTCR_CLIENT_SEND_MESSAGE    0x50
#define MTCR_CLIENT_SEND_PRIVATE    0x51
#define MTCR_CLIENT_GET_ONLINE_LIST 0x60

char *create_MTCR_socket(int, const char *);
int parse_MTCR_socket(const char *, int *, char **);

#endif
